- name: Create All Roboshop Parameters
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
        - {name: "param.dev.catalogue.MONGO", value: "true"}
        - {name: "param.dev.user.MONGO", value:"true}
  name: demo on loops
    hosts: localhost
    tasks:
      - name: Loop on List
        ansible.builtin.debug:
        msg: "Fruit Name - {{item}}"
        loop:
          - orange
          - apple
      - name: Loop on List of maps
        ansible.builtin.debug:
        msg: "Fruit Name - {{item.name}} , Count = {{item.count}}"
        loop:
          - { name: "orange", count: 100 }
          - { name: "apple", count: 50 }