- name: Create All Roboshop Parameters
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
        - {name: "param.dev.catalogue.MONGO", value: "true"}
        - {name: "param.dev.user.MONGO", value: "true"}
        - { name: "param.dev.docdb.USERNAME", value: "admin1" }
        - { name: "param.dev.docdb.PASSWORD", value: "admin123" }
        - { name: "param.dev.rds.USERNAME", value: "admin2" }
        - { name: "param.dev.rds.PASSWORD", value: "admin123" }


