- name: demo on loops
  hosts: localhost
  tasks:
    - name: loop on list
      ansible.builtin.debug:
        msg: "Fruit Name - {{items}}"
      loop:
        - orange
        - apple
    - name: loop on list of maps
      ansible.builtin.debug:
        msg: "Fruit Name - {{item.name}} , Count = {{item.count}}"
          - {name: "orange", count: 100}
          - {name: "apple", count: 50}