groups:
  - name: custom
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          project: workstation
        annotations:
          summary: InstanceDown
          description: InstanceDown
